### ISSUE TITLE
Will this library ever be updated with the newest Notificare SDK's?

### ISSUE THREAD

**Issue by LcTwisk** [Notificare/notificare-push-lib-react-native#1]

**Comment by jjonthemix** [comment]
Yes, that is our plan. We are rolling out the native SDK (iOS now in beta and Web, Android and tvOS will be in beta soon) and after that Xamarin, Cordova and React will be next as they are built on the top of the native ones.

**Comment by LcTwisk** [comment]
Alright thanks! Do you have a rough estimate on when you expect the update to be there? We're about to implement our own wrapper for RN since this library isn't updated for over a year. Would be nice if you guys could release a new version for every update to the native SDK 👍

**Comment by jjonthemix** [comment]
Our timeline points to end of May but might be even later. As these frameworks suffer constant breaking changes we have decided they should be open source so you are free to fork it or do a pull request if you feel generous or even wait for us (if it fits your timeline) to eventually work in updates for version 2.0 as it will break things. Regards.

**Comment by LcTwisk** [comment]
Cool!
